### ISSUE TITLE
Using gauseR for an environmental microbial community

### ISSUE THREAD

**Issue by dawsonphan** [adamtclark/gauseR#3]
Hi,

I have a microbial environmental dataset with relative abundances (values ranging from 0 to 1). I want to apply it to gauseR and graph the linear fit models (i.e. lm(prey_dN/Ndt ~ prey + predator)). The only issue is that because there are some zero-values, the per capita growth rate becomes NA, which makes it hard to graph the logistic model. Do you have any ideas to remedy this (i.e. data transformations)?

Cheers,
Dawson

**Comment by adamtclark** [comment]
Thanks for your interest! I'm afraid there aren't any data transformations that can help here, though there are a couple of potential "cheats". The problem is basically that any time an abundance drops to zero, that equates to an infinitely high rate of change, since in theory, the model only ever approaches zero asymptotically (though perhaps you already know this).

One solution is to just replace the zeros with a small number - I usually use the smallest non-zero observation (i.e. min(prey[prey>0]), since you can roughly treat that value as a "detection limit". That should work for rough visualisation, though can be a bit sketchy statistically, so I might not use this method in a publication.

The other solution would be to use the "lv_optim" function to find the parameter values. Basically, you can use solution #1 above to get starting estimates for the parameter values, and then plug those values into the optimiser function (as shown under the "# run optimizer" section in the ?lv_optim help function). For the data that you plug into the lv_optim function, you can leave the zeros in place, since that function actually simulates out the ODE and then just measures distances between observed and simulated values, which avoids the problem with dN/Ndt going to infinity.

Hope that this helps - lemme know if anything else comes up.
